language: python
sudo: false
cache:
  pip: true
  directories:
  - eggs
  - downloads
matrix:
  include:
    - python: 2.7
      env: PLONE_VERSION=4.3.x
    - python: 2.7
      env: PLONE_VERSION=5.0.x
    - python: 2.7
      env: PLONE_VERSION=5.1.x
    - python: 2.7
      env: PLONE_VERSION=5.2.x
    - python: 3.6
      env: PLONE_VERSION=5.2.x
    - python: 3.7
      env: PLONE_VERSION=5.2.x
      dist: xenial
before_install:
  - mkdir -p buildout-cache/downloads
  - mkdir -p buildout-cache/eggs
install:
  - virtualenv -p `which python` .
  - bin/pip install -r requirements-$PLONE_VERSION.txt
  - bin/buildout -N -c buildout-$PLONE_VERSION.cfg buildout:download-cache=downloads code-analysis:return-status-codes=True annotate
  - bin/buildout -N -c buildout-$PLONE_VERSION.cfg buildout:download-cache=downloads code-analysis:return-status-codes=True
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- firefox -v
script:
  - bin/code-analysis
  - bin/test
after_success:
  - bin/createcoverage
  - bin/pip install coverage
  - bin/python -m coverage.pickle2json
  - pip install coveralls
  - coveralls
