language: python
sudo: false
cache:
  pip: true
  directories:
  - eggs
  - downloads
python:
  - "2.7"
matrix:
  include:
    - python: "2.7"
      env: PLONE_VERSION=43
    - python: "2.7"
      env: PLONE_VERSION=51
    - python: "2.7"
      env: PLONE_VERSION=52
    - python: "3.7"
      env: PLONE_VERSION=52
      dist: xenial
  sudo: true
  fast_finish: true
before_install:
  - virtualenv -p `which python` .
  - mkdir -p $HOME/buildout-cache/{eggs,downloads}
  - mkdir $HOME/.buildout
  - echo "[buildout]" > $HOME/.buildout/default.cfg
  - echo "download-cache = $HOME/buildout-cache/downloads" >> $HOME/.buildout/default.cfg
  - echo "eggs-directory = $HOME/buildout-cache/eggs" >> $HOME/.buildout/default.cfg
  - bin/pip install -r requirements.txt -c constraints_plone$PLONE_VERSION.txt
#  - bin/buildout -N out:download-cache=downloads code-analysis:return-status-codes=True annotate
#  - bin/buildout -N buildout:download-cache=downloads code-analysis:return-status-codes=True
  - cp test_plone$PLONE_VERSION.cfg buildout.cfg

install:
 - bin/buildout -N -t 3 code-analysis:return-status-codes=True annotate
 - bin/buildout -N -t 3 code-analysis:return-status-codes=True

before_script:
- 'export DISPLAY=:99.0'
- Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
- sleep 3
- firefox -v

script:
# do code-analysis only on latest plone because there's
# a strange error with configparser in version < 5.1
  - echo $PLONE_VERSION | grep -v 5.2.x || bin/code-analysis
  - bin/test --all

after_success:
  - echo $PLONE_VERSION | grep -v 5.2.x || bin/createcoverage --output-dir=parts/test/coverage
  - echo $PLONE_VERSION | grep -v 5.2.x || bin/pip install coverage
  - echo $PLONE_VERSION | grep -v 5.2.x || bin/python -m coverage.pickle2json
  - echo $PLONE_VERSION | grep -v 5.2.x || bin/pip install -q coveralls
  - echo $PLONE_VERSION | grep -v 5.2.x || coveralls
