language: python
sudo: false
cache:
  pip: true
  directories:
  - eggs
  - downloads
matrix:
  include:
    - python: 2.7
      env: PLONE_VERSION=4.3.x
    - python: 2.7
      env: PLONE_VERSION=5.0.x
    - python: 2.7
      env: PLONE_VERSION=5.1.x
    - python: 2.7
      env: PLONE_VERSION=5.2.x
    - python: 3.6
      env: PLONE_VERSION=5.2.x
    - python: 3.7
      env: PLONE_VERSION=5.2.x
      dist: xenial
before_install:
  - mkdir -p buildout-cache/downloads
  - mkdir -p buildout-cache/eggs
install:
  - pip install -r requirements-$PLONE_VERSION.txt
  - buildout -Nc test-plone-$PLONE_VERSION.cfg
script:
  - bin/test
after_success:
  - bin/coverage.sh
  - pip install coveralls
  - coveralls
