# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Plone package

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        plone-version:
          - "6.0-dev"
          - "6.1-dev"
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"

    steps:
      - uses: actions/checkout@v4

      - name: Setup Plone ${{ matrix.plone-version }} with Python ${{ matrix.python-version }}
        uses: plone/setup-plone@v2.0.0
        with:
          python-version: ${{ matrix.python-version }}
          plone-version: ${{ matrix.plone-version }}

      - name: Install addon package, in editable mode, with pip
        run: |
          pip install tox

      - name: Run tests (located inside src)
        run: |
          tox -r
